name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'blue'

inputs:
  message:
    description: 'The message ("tweet") to post to twitter.'
    required: true
  consumer-key:
    description:
      'Consumer API key, available in the "Keys and tokens" section of your
      application in the Twitter Developer site.'
    required: true
  consumer-secret:
    description:
      'Consumer API secret key, available in the "Keys and tokens" section of
      your application in the Twitter Developer site.'
    required: true
  access-token:
    description:
      'Application access token, available in the "Keys and tokens" section of
      your application in the Twitter Developer site.'
    required: true
  access-token-secret:
    description:
      'Application access token secret, available in the "Keys and tokens"
      section of your application in the Twitter Developer site.'
    required: true
  bearer-token:
    description:
      'Application bearer token, available in the "Keys and tokens" section of
      your application in the Twitter Developer site.'
    required: true
outputs:
  tweetID:
    description: 'posted tweet ID'

runs:
  using: node20
  main: dist/index.js
